### ISSUE TITLE
Will there be a detailed instuction on how to implement the code

### ISSUE THREAD

**Issue by Xinxinatg** [dpernes/FCN-rLSTM#1]
I am trying to implement the code, whereas it's bit difficult to read the code and run it from scratch. Will there be any chance that the detailed instruction will be attached? Thanks in advance.

**Comment by dpernes** [comment]
What exactly do you want to implement?

**Comment by Xinxinatg** [comment]
Like how to import data, how to set up the hierarchy of folders? And how to set up the hyperparameters when training and testing? I am also thinking of applying this code on crowd counting dataset. Thanks a lot for your reply!

**Comment by Xinxinatg** [comment]
> What exactly do you want to implement?

I think I figured it out almost. Just started learning deep learning 2 months ago, so bit confused when trying to run the codes. But just one quick question, the paper on which the code is based talked about this can also be implemented on UCSD pedestrian counting dataset, have you ever tried to implement this part on crowd counting as well?

**Comment by dpernes** [comment]
> I think I figured it out almost.

Yeah, it should be pretty obvious from the arguments of train and test scripts. Just note that train_seq and test_seq do use sequential data (i.e. video) and therefore include the LSTM part. The versions without the suffix *_seq treat each frame separately, and therefore no LSTM is used.

> this can also be implemented on UCSD pedestrian counting dataset, have you ever tried to implement this part on crowd counting as well?

Yes, I have. It's pretty straightforward to adapt the code for this dataset and it works nicely there too.

**Comment by Xinxinatg** [comment]
Thanks heaps!
